import type { Agent } from "@/lib/types";

export const agents: Agent[] = [
  {
    id: "qe-specialist",
    name: "QE Specialist",
    tier: "local",
    description: "Test automation, coverage analysis, and QA strategy.",
    keywords: [
      "test",
      "tests",
      "testing",
      "coverage",
      "automation",
      "automate",
      "e2e",
      "regression",
      "qa",
      "flaky",
    ],
    color: "var(--ordino-orange)",
  },
  {
    id: "code-quality",
    name: "Code Quality",
    tier: "local",
    description: "Static analysis, code smells, complexity, and review quality.",
    keywords: [
      "code quality",
      "quality of the code",
      "lint",
      "linting",
      "complexity",
      "tech debt",
      "technical debt",
      "smell",
      "review",
      "maintainability",
    ],
    color: "var(--ordino-pink)",
  },
  {
    id: "metrics-analyst",
    name: "Metrics Analyst",
    tier: "local",
    description: "Quality metrics, dashboards, and trend reporting.",
    keywords: [
      "metric",
      "metrics",
      "dashboard",
      "report",
      "trend",
      "velocity",
      "kpi",
      "defect rate",
      "escape rate",
    ],
    color: "var(--ordino-purple)",
  },
  {
    id: "deep-reasoning",
    name: "Deep Reasoning",
    tier: "cloud",
    description: "Feature planning, architecture trade-offs, and open-ended reasoning.",
    keywords: [
      "plan",
      "planning",
      "feature",
      "requirement",
      "requirements",
      "architecture",
      "design",
      "spec",
      "roadmap",
      "trade-off",
      "tradeoff",
    ],
    color: "var(--ordino-blue)",
  },
];

export const defaultAgentId = "deep-reasoning";
